'use strict'

import { equal } from 'assert'
import { Var, Const, Neg, Exp, Ln, Sin, Cos, Tan } from '../src/autograd.js'

function assertFloatEqual(actual, expected) {
  equal(Math.abs(actual - expected) < 1e-8, true)
}

describe('test of eval and diff calculation', () => {
  it('case 1', () => {
    const x = Var()
    const y = Const(-3).mul(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    equal(y.value, -9)
    equal(x.grad, -3)
  })
  it('case 2', () => {
    const x = Var()
    const y = Var(155)
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    equal(x.value, 3)
    equal(y.value, 155)
    equal(x.grad, 0)
    equal(y.grad, 1)
  })
  it('case 3', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const r = x.mul(y).add(z).add(x.add(y).mul(z))
    const graph = r.toComputeGraph()
    graph.eval([x, y, z], [5, 4, 7])
    equal(r.value, 90)
    equal(x.grad, 11)
    equal(y.grad, 12)
    equal(z.grad, 10)
  })
  it('case 4', () => {
    const x = Var()
    const y = Var()
    const u = x.mul(y)
    const v = u.mul(u)
    const r = v.add(v)
    const graph = r.toComputeGraph()
    graph.eval([x, y], [23, 77])
    equal(r.value, 6272882)
    equal(x.grad, 545468)
    equal(y.grad, 162932)
  })
  it('case 5', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const w = Var()
    const r = x.mul(y).add(Const(3).mul(z)).add(Const(6).mul(w))
      .mul(Const(12).add(y.mul(z)).add(Const(6).mul(w)))
      .add(Const(10).mul(x).mul(y.add(z)).mul(w.add(Const(3))))
    const graph = r.toComputeGraph()
    graph.eval([x, y, z, w], [2, -3, 11, 7])
    equal(r.value, 3049)
    equal(x.grad, 737)
    equal(y.grad, 1001)
    equal(z.grad, 56)
    equal(w.grad, 700)
  })
  it('case 6', () => {
    const x = Var()
    const y = Var()
    const u = x.add(y)
    const v = x.mul(y)
    const r = Const(2).mul(u).mul(v).mul(v).add(Const(3).mul(u).mul(u).mul(v)).add(Const(4))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [12, 13])
    equal(u.value, 25)
    equal(v.value, 156)
    equal(r.value, 1509304)
    equal(u.grad, 72072)
    equal(v.grad, 17475)
    equal(x.grad, 299247)
    equal(y.grad, 281772)
  })
  it('case 7', () => {
    const x = Var()
    const y = Var()
    const u = x.add(y)
    const v = x.mul(y)
    const a = Const(3).mul(u).add(Const(2).mul(v))
    const b = Const(7).mul(u).mul(v)
    const r = x.add(y).add(u).add(v).add(a).add(b).add(x.mul(y).mul(u).mul(v).mul(a).mul(b))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [-3, 2])
    equal(r.value, 22699)
    equal(x.grad, -78669)
    equal(y.grad, -6829)
  })
  it('case 8', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const u = x.add(y).add(z)
    const v = x.mul(y).add(y.mul(z)).add(x.mul(z))
    const w = x.mul(y).mul(z).add(Const(-7))
    const r = Const(2).mul(x)
      .add(Const(7).mul(u.mul(v).add(w)))
      .sub(Const(16).mul(v.add(w)))
      .add(w.mul(u))
      .sub(Const(1).mul(u).mul(v).mul(w))
      .add(Const(3).mul(y))
      .add(Const(4).mul(z))
    const graph = r.toComputeGraph()
    graph.eval([x, y, z], [2, 7, -11])
    equal(r.value, 31672)
    equal(x.grad, 906)
    equal(y.grad, -7288)
    equal(z.grad, -20139)
  })
  it('case 9', () => {
    const x = Var()
    const y = Const(1).div(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    equal(y.value, 1 / 3)
    equal(x.grad, -1 / 9)
  })
  it('case 10', () => {
    const x = Var()
    const y = Var()
    const r = x.div(y)
    const graph = r.toComputeGraph()
    graph.eval([x, y], [37, 12])
    equal(r.value, 37 / 12)
    equal(x.grad, 1 / 12)
    equal(y.grad, -37 / (12 * 12))
  })
  it('case 11', () => {
    const x = Var()
    const y = Var()
    const r = x.add(y).div(x.sub(y))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [3, -4])
    equal(r.value, -1 / 7)
    equal(x.grad, 8 / 49)
    equal(y.grad, 6 / 49)
  })
  it('case 12', () => {
    const x = Var()
    const y = Var()
    const r = x.add(y).div(x.sub(y))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [3, -4])
    equal(r.value, -1 / 7)
    equal(x.grad, 8 / 49)
    equal(y.grad, 6 / 49)
  })
  it('case 13', () => {
    const x = Var()
    const y = Var()
    const r = Const(1).div(Const(1).add(x.mul(y)))
      .sub(x.mul(x).add(y.mul(y)).div(Const(2).mul(x).mul(y)))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [3, -4])
    equal(r.value, 251 / 264)
    assertFloatEqual(x.grad, -559 / 8712)
    assertFloatEqual(y.grad, -1135 / 11616)
  })
  it('case 14', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const r = x.div(y).div(z)
    const graph = r.toComputeGraph()
    graph.eval([x, y, z], [3, -4, 2])
    equal(r.value, -3 / 8)
    equal(x.grad, -1 / 8)
    equal(y.grad, -3 / 32)
    equal(z.grad, 3 / 16)
  })
  it('case 15', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const r = x.div(y.div(z))
    const graph = r.toComputeGraph()
    graph.eval([x, y, z], [3, -4, 2])
    equal(r.value, -3 / 2)
    equal(x.grad, -1 / 2)
    equal(y.grad, -3 / 8)
    equal(z.grad, -3 / 4)
  })
  it('case 16', () => {
    const x = Var()
    const y = Var()
    const r = x.div(y).mul(y)
    const graph = r.toComputeGraph()
    graph.eval([x, y], [3, 2])
    equal(r.value, 3)
    equal(x.grad, 1)
    equal(y.grad, 0)
  })
  it('case 17', () => {
    const x = Var()
    const y = Var()
    const r = x.mul(y).div(y)
    const graph = r.toComputeGraph()
    graph.eval([x, y], [3, 2])
    equal(r.value, 3)
    equal(x.grad, 1)
    equal(y.grad, 0)
  })
  it('case 18', () => {
    const x = Var()
    const y = Var()
    const u = x.div(y)
    const v = y.div(x)
    const r = Const(1).div(x)
      .sub(Const(2).mul(u).add(Const(3).mul(v))
        .div(Const(5).mul(u).sub(Const(7).mul(v)).add(Const(2))))
      .add(Const(1).div(y))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [7, 3])
    assertFloatEqual(r.value, -55 / 672)
    assertFloatEqual(x.grad, 551 / 12544)
    assertFloatEqual(y.grad, -4213 / 16128)
  })
  it('case 19', () => {
    const x = Var()
    const y = x.pow(Const(4))
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    equal(y.value, 81)
    equal(x.grad, 108)
  })
  it('case 20', () => {
    const x = Var()
    const y = Const(4).pow(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    equal(y.value, 64)
    equal(x.grad, 64 * Math.log(4))
  })
  it('case 21', () => {
    const x = Var()
    const y = Var()
    const r = x.pow(y)
    const graph = r.toComputeGraph()
    graph.eval([x, y], [5, 3])
    equal(r.value, 125)
    equal(x.grad, 75)
    equal(y.grad, 125 * Math.log(5))
  })
  it('case 22', () => {
    const x = Var()
    const y = Var()
    const r = x.add(y).pow(Const(2).mul(x).sub(Const(3).mul(y)))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [2, 3])
    assertFloatEqual(r.value, 1 / 3125)
    assertFloatEqual(x.grad, (Math.log(25) - 1) / 3125)
    assertFloatEqual(y.grad, (-3 * Math.log(5) - 1) / 3125)
  })
  it('case 23', () => {
    const x = Var()
    const y = x.pow(Const(3))
      .sub(Const(4).pow(x))
      .add(x.add(Const(7)).mul(x.add(Const(1))).div(Const(2).mul(x).sub(Const(3))))
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    assertFloatEqual(y.value, -71 / 3)
    assertFloatEqual(x.grad, 205 / 9 - 64 * Math.log(4))
  })
  it('case 24', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const r = x.pow(y).pow(z)
    const graph = r.toComputeGraph()
    graph.eval([x, y, z], [4, 3, 2])
    equal(r.value, 4096)
    equal(x.grad, 6144)
    equal(y.grad, 8192 * Math.log(4))
    equal(z.grad, 4096 * Math.log(64))
  })
  it('case 25', () => {
    const x = Var()
    const y = Var()
    const z = Var()
    const r = x.pow(y.pow(z))
    const graph = r.toComputeGraph()
    graph.eval([x, y, z], [4, 3, 2])
    equal(r.value, 262144)
    equal(x.grad, 589824)
    equal(y.grad, 1572864 * Math.log(4))
    equal(z.grad, 2359296 * Math.log(3) * Math.log(4))
  })
  it('case 26', () => {
    const x = Var()
    const y = Neg(x).add(Const(3))
    const graph = y.toComputeGraph()
    graph.eval([x], [13])
    equal(y.value, -10)
    equal(x.grad, -1)
  })
  it('case 27', () => {
    const x = Var()
    const u = x
    const v = Neg(x)
    const r = u.add(v)
    const graph = r.toComputeGraph()
    graph.eval([x], [5])
    equal(r.value, 0)
    equal(x.grad, 0)
  })
  it('case 28', () => {
    const x = Var()
    const y = Exp(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [3])
    equal(y.value, Math.exp(3))
    equal(x.grad, Math.exp(3))
  })
  it('case 29', () => {
    const x = Var()
    const y = Var()
    const r = Exp(Neg(x.pow(Const(2)).add(y.pow(Const(2)))))
    const graph = r.toComputeGraph()
    graph.eval([x, y], [3, -2])
    equal(r.value, 1 / Math.exp(13))
    assertFloatEqual(x.grad, -6 / Math.exp(13))
    assertFloatEqual(y.grad, 4 / Math.exp(13))
  })
  it('case 30', () => {
    const x = Var()
    const y = Ln(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [17])
    equal(y.value, Math.log(17))
    equal(x.grad, 1 / 17)
  })
  it('case 31', () => {
    const x = Var()
    const y = Ln(x.pow(Const(2)).sub(Const(3).mul(x)).add(Const(2)))
    const graph = y.toComputeGraph()
    graph.eval([x], [5])
    equal(y.value, Math.log(12))
    assertFloatEqual(x.grad, 7 / 12)
  })
  it('case 32', () => {
    const x = Var()
    const y = Sin(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [10])
    equal(y.value, Math.sin(10))
    assertFloatEqual(x.grad, Math.cos(10))
  })
  it('case 33', () => {
    const x = Var()
    const y = Cos(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [20])
    equal(y.value, Math.cos(20))
    assertFloatEqual(x.grad, -Math.sin(20))
  })
  it('case 34', () => {
    const x = Var()
    const y = Tan(x)
    const graph = y.toComputeGraph()
    graph.eval([x], [5])
    equal(y.value, Math.tan(5))
    assertFloatEqual(x.grad, 1 / (Math.cos(5) * Math.cos(5)))
  })
})

describe('special test', () => {
  it('case 1', () => {
    const x = Var()
    const y = x.mul(x)
    const graph = y.toComputeGraph()

    graph.eval([x], [3])
    equal(y.value, 9)
    equal(x.grad, 6)

    graph.eval([x], [4])
    equal(y.value, 16)
    equal(x.grad, 8)
  })
})
